/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import database.connection;
import java.io.File;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author nurul
 */
public class Laporan extends javax.swing.JFrame {

    /**
     * Creates new form laporan
     */
    public Laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void previewReport(String filename, HashMap parameter, String jenis) {
        try {
            File fileReport = new File("src\\laporan\\" + filename);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(fileReport.getPath());
            parameter.put("tgl1", tgl1.getDate());
            parameter.put("tgl2", tgl2.getDate());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, connection.getConn());
            JasperViewer.viewReport(jasperPrint, false);

        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, "Error " + e);
            System.err.println("Error " + e);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbReport = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        tgl1 = new com.toedter.calendar.JDateChooser();
        tgl2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbReport.setBackground(new java.awt.Color(28, 31, 44));
        cbReport.setForeground(new java.awt.Color(255, 255, 255));
        cbReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Pembayaran Siswa", "Pendapatan Non Siswa", "Pengeluaran Sekolah", "Surat Masuk", "Surat Keluar" }));
        cbReport.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbReportItemStateChanged(evt);
            }
        });
        cbReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbReportActionPerformed(evt);
            }
        });
        jPanel1.add(cbReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 173, 149, -1));

        jButton1.setBackground(new java.awt.Color(28, 31, 44));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cetak Laporan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 150, -1));
        jPanel1.add(tgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 94, 149, -1));
        jPanel1.add(tgl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 135, 149, -1));

        jLabel1.setText("Masukan Tanggal");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 94, -1, -1));

        jLabel2.setText("s.d");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 135, -1, -1));

        jLabel3.setText("Pilih Laporan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 176, 90, -1));

        jButton2.setBackground(new java.awt.Color(28, 31, 44));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 150, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Laporan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tgl1.getDate().equals("") || tgl2.getDate().equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan Tanggal Terlebih Dahulu!", "SDIT Bahrul Fikri", JOptionPane.INFORMATION_MESSAGE);
        } else {
            HashMap parameter = new HashMap();
            //boolean isError = false;
            int ok = JOptionPane.showConfirmDialog(null, "Ingin Mencetak Laporan?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if /*(!isError)*/ (ok == 0) {
                String LP = cbReport.getSelectedItem().toString();
                switch (LP) {
                    case "Pembayaran Siswa":
                        previewReport("laporanpembayaran.jasper", parameter, LP);
                        break;
                    case "Pendapatan Non Siswa":
                        previewReport("laporanpendapatannonsiswa.jasper", parameter, LP);
                        break;
                    case "Pengeluaran Sekolah":
                        previewReport("laporanpengeluaransekolah.jasper", parameter, LP);
                        break;
                    case "Surat Masuk":
                        previewReport("laporansuratmasuk.jasper", parameter, LP);
                        break;
                    case "Surat Keluar":
                        previewReport("laporansuratkeluar.jasper", parameter, LP);
                        break;
                    default:
                        JOptionPane.showMessageDialog(null, "Anda belum memilih laporan!");
                        break;
                }
            } else {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbReportItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbReportItemStateChanged
        String LP = cbReport.getSelectedItem().toString();
        if (LP.equals("Pembayaran Siswa") || LP.equals("Pendapatan Non Siswa") || LP.equals("Pengeluaran Sekolah") || LP.equals("Surat Masuk") || LP.equals("Surat Keluar")) {
            // dateEnabled(false);
        } else {
            //dateEnabled(true);
            //ttgl_dari.requestFocus();
        }
    }//GEN-LAST:event_cbReportItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Laporan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbReport;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser tgl1;
    private com.toedter.calendar.JDateChooser tgl2;
    // End of variables declaration//GEN-END:variables
}
